---
title: "7.1 darkdiv test"
author: "TG"
date: "2023-01-29"
output: html_document
---

```{r}
library(DarkDiv)
library(tidyverse)
library(vegan)
library(plotrix)
```

```{r}
load("G:/My Drive/PHD/chapter 3 MPA dd/Meddata-DD/clean_dd_medata.rdata")

clean_dd_medata<-medata # keep the original

medata<-medata %>% select(1:22) # keep only metadate and abundances

medata<-medata %>% group_by(across(1:21)) %>% summarise(amount = sum(sp.n)) %>% ungroup() # sum ind from the same sp in each transect

medata <-medata %>% group_by(alt_basin,species) %>% mutate(occupancy = n())  

medata<-medata %>% filter(occupancy > 3)

medata$occupancy<-NULL

medata_wide<-spread(medata,species,amount,fill = 0) # convert to wide format




#dd<-DarkDiv(medata_wide[,21:ncol(medata_wide)])
```



```{r}
index_list<-list()
data_list<-list()

for (i in unique(medata_wide$alt_basin)) {
 
   basin_data<-medata_wide %>% filter(alt_basin == i)
   dd<-DarkDiv(basin_data[,21:ncol(basin_data)],method = "Hypergeometric")
   
   index_list[[i]]<-dd
   
   dd_dark<-dd[["Dark"]]
   dd_dark<-as.data.frame(dd_dark)
   dd_dark<-dd_dark %>% mutate("dark"=rowSums(dd_dark,na.rm = T))
   dd_dark_sum<- dd_dark %>% select(dark)
   
   dd_pool<-dd[["Pool"]]
   dd_pool<-as.data.frame(dd_pool)
   dd_pool<-dd_pool %>% mutate("total"=rowSums(dd_pool,na.rm = T))
   dd_pool_sum<-dd_pool %>% select(total)
   
   medata_dd<-basin_data[,1:20]
   medata_dd<-as.data.frame(medata_dd)

   medata_dd<-bind_cols(medata_dd,dd_pool_sum)
   medata_dd<-bind_cols(medata_dd,dd_dark_sum)

   medata_dd$observed_richness<-medata_dd$total-medata_dd$dark
   
   data_list[[i]]<-medata_dd
}

dd_data<-bind_rows(data_list)
```

```{r}
#sp_richness <- medata %>% group_by(unique_trans_id) %>% summarise(sp = n_distinct(species))
```

plot

```{r}



protection <- gather(dd_data,type,richness,21:23)
protection <- protection %>% arrange(unique_trans_id)


protection <- protection %>%
  group_by(protection,type) %>%
  summarise("mean_richness"= mean(richness),
            "se"=std.error(richness)) 


protection %>%  na.omit() %>% filter(type != "total") %>% 
ggplot()+
       aes(x=protection,y = mean_richness,fill = type )+
  geom_bar(stat="identity")+ylab("Mean richness per transect")+
  scale_fill_manual(values = c("#1B2D48","#F7D54A"))+theme_classic()
```

```{r}
enf <- gather(dd_data,type,richness,21:23)
enf <- enf %>% arrange(unique_trans_id)


enf <- enf %>%
  group_by(enforcement,type) %>%
  summarise("mean_richness"= mean(richness),
            "se"=std.error(richness)) 


enf %>%  na.omit() %>% filter(type != "total") %>% 
ggplot()+
       aes(x=enforcement,y = mean_richness,fill = type )+
  geom_bar(stat="identity")+ylab("Mean richness per transect")+
  scale_fill_manual(values = c("#1B2D48","#F7D54A"))+theme_classic()

enf %>%  na.omit() %>% filter(type == "dark") %>% 
ggplot()+
       aes(x=enforcement,y = mean_richness,fill = type )+
  geom_bar(stat="identity",position=position_dodge(.9),fill = "#1B2D48")+
  geom_errorbar(aes(ymin=mean_richness-se, ymax=mean_richness+se), width=.2,
                 position=position_dodge(.9))+ylab("Mean Dark diversity per transect") +theme_classic()
```
fished vs non fished

```{r}

```

